### ISSUE TITLE
Failed building wheel for topologylayer

### ISSUE THREAD

**Issue by gongshichina** [bruel-gabrielsson/TopologyLayer#10]
Hi! When I run `pip install git+https://github.com/bruel-gabrielsson/TopologyLayer.git`, it occurs to `ERROR: Failed building wheel for topologylayer` 
I'll appreciate it if anyone can help!

Below is specific configuration:
**OS: ubuntu 16.4**
**python: 3.7**
**conda list as below**
```
(toplayer) shigong@1060:~$ conda list
WARNING: The conda.compat module is deprecated and will be removed in a future release.
# packages in environment at /home/shigong/anaconda3/envs/toplayer:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2019.3.9                 py37_0    defaults
cffi                      1.12.3           py37h2e261b9_0    defaults
cudatoolkit               8.0                           3    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
cycler                    0.10.0                   py37_0    defaults
dbus                      1.13.6               h746ee38_0    defaults
expat                     2.2.6                he6710b0_0    defaults
fontconfig                2.13.0               h9420a91_0    defaults
freetype                  2.9.1                h8a8886c_1    defaults
glib                      2.56.2               hd408876_0    defaults
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
glib                      2.56.2               hd408876_0    defaults                                                                                                                               [0/1061]
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb453b48_1    defaults
icu                       58.2                 h9c2bf20_1    defaults
intel-openmp              2019.3                      199    defaults
jpeg                      9b                   h024ee3a_2    defaults
kiwisolver                1.1.0            py37he6710b0_0    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libpng                    1.6.37               hbc83047_0    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
libtiff                   4.0.10               h2733197_2    defaults
libuuid                   1.0.3                h1bed415_2    defaults
libxcb                    1.13                 h1bed415_1    defaults
libxml2                   2.9.9                he19cac6_0    defaults
matplotlib                3.1.0            py37h5429711_0    defaults
mkl                       2019.3                      199    defaults
mkl_fft                   1.0.12           py37ha843d7b_0    defaults
mkl_random                1.0.2            py37hd81dba3_0    defaults
ncurses                   6.1                  he6710b0_1    defaults
ninja                     1.7.2                         0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
numpy                     1.16.4           py37h7e9f1db_0    defaults
numpy-base                1.16.4           py37hde5b4d6_0    defaults
olefile                   0.46                     py37_0    defaults
openssl                   1.1.1c               h7b6447c_1    defaults
pcre                      8.43                 he6710b0_0    defaults
pillow                    6.0.0            py37h34e0f95_0    defaults
pip                       19.1.1                   py37_0    defaults
pycparser                 2.19                     py37_0    defaults
pyparsing                 2.4.0                      py_0    defaults
pyqt                      5.9.2            py37h05f1152_2    defaults
python                    3.7.3                h0371630_0    defaults
python-dateutil           2.8.0                    py37_0    defaults
pytorch                   1.0.1           py3.7_cuda8.0.61_cudnn7.1.2_2    pytorch
pytz                      2019.1                     py_0    defaults
qt                        5.9.7                h5867ecd_1    defaults
readline                  7.0                  h7b6447c_5    defaults
scipy                     1.2.1            py37h7c811a0_0    defaults
setuptools                41.0.1                   py37_0    defaults
sip                       4.19.8           py37hf484d3e_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.28.0               h7b6447c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
torchvision               0.2.2                      py_3    pytorch
tornado                   6.0.2            py37h7b6447c_0    defaults
wheel                     0.33.4                   py37_0    defaults
xz                        5.2.4                h14c3975_4    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.3.7                h0b5b093_0    defaults

```
**verbose output as below**
```
(toplayer) shigong@1060:~$ pip install --verbose git+https://github.com/bruel-gabrielsson/TopologyLayer.git
Created temporary directory: /tmp/pip-ephem-wheel-cache-e6xo6ysb
Created temporary directory: /tmp/pip-req-tracker-r_iwud0j
Created requirements tracker '/tmp/pip-req-tracker-r_iwud0j'
Created temporary directory: /tmp/pip-install-6bqrovoj
Collecting git+https://github.com/bruel-gabrielsson/TopologyLayer.git
  Created temporary directory: /tmp/pip-req-build-epvzlx9e
  Cloning https://github.com/bruel-gabrielsson/TopologyLayer.git to /tmp/pip-req-build-epvzlx9e
  Running command git clone -q https://github.com/bruel-gabrielsson/TopologyLayer.git /tmp/pip-req-build-epvzlx9e
  Added git+https://github.com/bruel-gabrielsson/TopologyLayer.git to build tracker '/tmp/pip-req-tracker-r_iwud0j'
    Running setup.py (path:/tmp/pip-req-build-epvzlx9e/setup.py) egg_info for package from git+https://github.com/bruel-gabrielsson/TopologyLayer.git
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/topologylayer.egg-info
    writing pip-egg-info/topologylayer.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/topologylayer.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/topologylayer.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/topologylayer.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/topologylayer.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/topologylayer.egg-info/SOURCES.txt'
  Source in /tmp/pip-req-build-epvzlx9e has version 0.0.0, which satisfies requirement topologylayer==0.0.0 from git+https://github.com/bruel-gabrielsson/TopologyLayer.git
  Removed topologylayer==0.0.0 from git+https://github.com/bruel-gabrielsson/TopologyLayer.git from build tracker '/tmp/pip-req-tracker-r_iwud0j'
Building wheels for collected packages: topologylayer
  Created temporary directory: /tmp/pip-wheel-4mdaeifm
  Building wheel for topologylayer (setup.py) ...   Destination directory: /tmp/pip-wheel-4mdaeifm
  Running command /home/shigong/anaconda3/envs/toplayer/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-epvzlx9e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__fi
le__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-4mdaeifm --python-tag cp37
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/topologylayer
  copying topologylayer/__init__.py -> build/lib.linux-x86_64-3.7/topologylayer
  creating build/lib.linux-x86_64-3.7/topologylayer/functional
  copying topologylayer/functional/alpha_dionysus.py -> build/lib.linux-x86_64-3.7/topologylayer/functional
  copying topologylayer/functional/sublevel.py -> build/lib.linux-x86_64-3.7/topologylayer/functional
  copying topologylayer/functional/flag.py -> build/lib.linux-x86_64-3.7/topologylayer/functional
  copying topologylayer/functional/utils_dionysus.py -> build/lib.linux-x86_64-3.7/topologylayer/functional
  copying topologylayer/functional/rips_dionysus.py -> build/lib.linux-x86_64-3.7/topologylayer/functional
  copying topologylayer/functional/__init__.py -> build/lib.linux-x86_64-3.7/topologylayer/functional
  copying topologylayer/functional/levelset_dionysus.py -> build/lib.linux-x86_64-3.7/topologylayer/functional
  creating build/lib.linux-x86_64-3.7/topologylayer/nn
  copying topologylayer/nn/alpha_dionysus.py -> build/lib.linux-x86_64-3.7/topologylayer/nn
  copying topologylayer/nn/features.py -> build/lib.linux-x86_64-3.7/topologylayer/nn
  copying topologylayer/nn/rips.py -> build/lib.linux-x86_64-3.7/topologylayer/nn
  copying topologylayer/nn/alpha.py -> build/lib.linux-x86_64-3.7/topologylayer/nn
copying topologylayer/nn/rips.py -> build/lib.linux-x86_64-3.7/topologylayer/nn                                                                                                                  [150/994]
  copying topologylayer/nn/alpha.py -> build/lib.linux-x86_64-3.7/topologylayer/nn
  copying topologylayer/nn/levelset.py -> build/lib.linux-x86_64-3.7/topologylayer/nn
  copying topologylayer/nn/rips_dionysus.py -> build/lib.linux-x86_64-3.7/topologylayer/nn
  copying topologylayer/nn/__init__.py -> build/lib.linux-x86_64-3.7/topologylayer/nn
  copying topologylayer/nn/levelset_dionysus.py -> build/lib.linux-x86_64-3.7/topologylayer/nn
  creating build/lib.linux-x86_64-3.7/topologylayer/util
  copying topologylayer/util/construction.py -> build/lib.linux-x86_64-3.7/topologylayer/util
  copying topologylayer/util/plot_dionysus.py -> build/lib.linux-x86_64-3.7/topologylayer/util
  copying topologylayer/util/__init__.py -> build/lib.linux-x86_64-3.7/topologylayer/util
  copying topologylayer/util/star_dionysus.py -> build/lib.linux-x86_64-3.7/topologylayer/util
  copying topologylayer/util/process.py -> build/lib.linux-x86_64-3.7/topologylayer/util
  copying topologylayer/util/flag_dionysus.py -> build/lib.linux-x86_64-3.7/topologylayer/util
  running build_ext
  building 'topologylayer.functional.cohom_cpp' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/topologylayer
  creating build/temp.linux-x86_64-3.7/topologylayer/functional
  creating build/temp.linux-x86_64-3.7/topologylayer/functional/cohom_cpp
  gcc -pthread -B /home/shigong/anaconda3/envs/toplayer/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/tmp/pip-req-build-epvzlx9e/topologylayer/f
unctional/cohom_cpp/ -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/torch/csrc/
api/include -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/TH -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/THC -I/home/shigo
ng/anaconda3/envs/toplayer/include/python3.7m -c topologylayer/functional/cohom_cpp/pybind.cpp -o build/temp.linux-x86_64-3.7/topologylayer/functional/cohom_cpp/pybind.o -std=c++11 -DTORCH_API_INCLUDE_EXT
ENSION_H -DTORCH_EXTENSION_NAME=cohom_cpp -D_GLIBCXX_USE_CXX11_ABI=0
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  gcc -pthread -B /home/shigong/anaconda3/envs/toplayer/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/tmp/pip-req-build-epvzlx9e/topologylayer/f
unctional/cohom_cpp/ -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/torch/csrc/
api/include -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/TH -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/THC -I/home/shigo
ng/anaconda3/envs/toplayer/include/python3.7m -c topologylayer/functional/cohom_cpp/cohom.cpp -o build/temp.linux-x86_64-3.7/topologylayer/functional/cohom_cpp/cohom.o -std=c++11 -DTORCH_API_INCLUDE_EXTEN
SION_H -DTORCH_EXTENSION_NAME=cohom_cpp -D_GLIBCXX_USE_CXX11_ABI=0
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  gcc -pthread -B /home/shigong/anaconda3/envs/toplayer/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/tmp/pip-req-build-epvzlx9e/topologylayer/f
unctional/cohom_cpp/ -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/torch/csrc/
api/include -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/TH -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/THC -I/home/shigo
ng/anaconda3/envs/toplayer/include/python3.7m -c topologylayer/functional/cohom_cpp/complex.cpp -o build/temp.linux-x86_64-3.7/topologylayer/functional/cohom_cpp/complex.o -std=c++11 -DTORCH_API_INCLUDE_E
XTENSION_H -DTORCH_EXTENSION_NAME=cohom_cpp -D_GLIBCXX_USE_CXX11_ABI=0
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  gcc -pthread -B /home/shigong/anaconda3/envs/toplayer/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/tmp/pip-req-build-epvzlx9e/topologylayer/f
unctional/cohom_cpp/ -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/torch/csrc/
api/include -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/TH -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/THC -I/home/shigo
ng/anaconda3/envs/toplayer/include/python3.7m -c topologylayer/functional/cohom_cpp/cocycle.cpp -o build/temp.linux-x86_64-3.7/topologylayer/functional/cohom_cpp/cocycle.o -std=c++11 -DTORCH_API_INCLUDE_E
XTENSION_H -DTORCH_EXTENSION_NAME=cohom_cpp -D_GLIBCXX_USE_CXX11_ABI=0
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  In file included from topologylayer/functional/cohom_cpp/cocycle.cpp:1:0:
  topologylayer/functional/cohom_cpp/cocycle.h:10:3: error: ‘size_t’ does not name a type
     size_t index;
     ^
  topologylayer/functional/cohom_cpp/cocycle.h: In constructor ‘Cocycle::Cocycle()’:
  topologylayer/functional/cohom_cpp/cocycle.h:17:15: error: class ‘Cocycle’ does not have any field named ‘index’
     Cocycle() : index(-1){}
                 ^
  topologylayer/functional/cohom_cpp/cocycle.h: In constructor ‘Cocycle::Cocycle(int)’:
topologylayer/functional/cohom_cpp/cocycle.h:20:20: error: class ‘Cocycle’ does not have any field named ‘index’
     Cocycle(int x) : index(x) {cochain.push_back(x); }
                      ^
  topologylayer/functional/cohom_cpp/cocycle.h: In constructor ‘Cocycle::Cocycle(int, std::vector<int>)’:
  topologylayer/functional/cohom_cpp/cocycle.h:21:41: error: class ‘Cocycle’ does not have any field named ‘index’
     Cocycle(int x, std::vector<int> y) :  index(x) , cochain(y) {}
                                           ^
  topologylayer/functional/cohom_cpp/cocycle.cpp: In member function ‘void Cocycle::print()’:
  topologylayer/functional/cohom_cpp/cocycle.cpp:86:33: error: too many arguments to function ‘void pybind11::print(Args&& ...) [with pybind11::return_value_policy policy = (pybind11::return_value_policy)
1u; Args = {}]’
    py::print(index, " : ", cochain);
                                   ^
  In file included from /home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/pybind.h:6:0,
                   from /home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/python.h:7,
                   from /home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/torch/extension.h:6,
                   from topologylayer/functional/cohom_cpp/cocycle.cpp:4:
  /home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/pybind11/pybind11.h:1747:6: note: declared here
   void print(Args &&...args) {
        ^
  error: command 'gcc' failed with exit status 1
error
  ERROR: Failed building wheel for topologylayer
  Running setup.py clean for topologylayer
  Running command /home/shigong/anaconda3/envs/toplayer/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-epvzlx9e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__fi
le__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
  running clean
  removing 'build/temp.linux-x86_64-3.7' (and everything under it)
  removing 'build/lib.linux-x86_64-3.7' (and everything under it)
  'build/bdist.linux-x86_64' does not exist -- can't clean it
  'build/scripts-3.7' does not exist -- can't clean it
  removing 'build'
Failed to build topologylayer
Installing collected packages: topologylayer
  Created temporary directory: /tmp/pip-record-jn57soax
    Running command /home/shigong/anaconda3/envs/toplayer/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-epvzlx9e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__
file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-jn57soax/install-record.txt --single-version-externall
y-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/topologylayer
    copying topologylayer/__init__.py -> build/lib.linux-x86_64-3.7/topologylayer
    creating build/lib.linux-x86_64-3.7/topologylayer/functional
    copying topologylayer/functional/alpha_dionysus.py -> build/lib.linux-x86_64-3.7/topologylayer/functional
    copying topologylayer/functional/sublevel.py -> build/lib.linux-x86_64-3.7/topologylayer/functional
    copying topologylayer/functional/flag.py -> build/lib.linux-x86_64-3.7/topologylayer/functional
    copying topologylayer/functional/utils_dionysus.py -> build/lib.linux-x86_64-3.7/topologylayer/functional
    copying topologylayer/functional/rips_dionysus.py -> build/lib.linux-x86_64-3.7/topologylayer/functional
 copying topologylayer/functional/utils_dionysus.py -> build/lib.linux-x86_64-3.7/topologylayer/functional                                                                                       [50/994]
    copying topologylayer/functional/rips_dionysus.py -> build/lib.linux-x86_64-3.7/topologylayer/functional
    copying topologylayer/functional/__init__.py -> build/lib.linux-x86_64-3.7/topologylayer/functional
    copying topologylayer/functional/levelset_dionysus.py -> build/lib.linux-x86_64-3.7/topologylayer/functional
    creating build/lib.linux-x86_64-3.7/topologylayer/nn
    copying topologylayer/nn/alpha_dionysus.py -> build/lib.linux-x86_64-3.7/topologylayer/nn
    copying topologylayer/nn/features.py -> build/lib.linux-x86_64-3.7/topologylayer/nn
    copying topologylayer/nn/rips.py -> build/lib.linux-x86_64-3.7/topologylayer/nn
    copying topologylayer/nn/alpha.py -> build/lib.linux-x86_64-3.7/topologylayer/nn
    copying topologylayer/nn/levelset.py -> build/lib.linux-x86_64-3.7/topologylayer/nn
    copying topologylayer/nn/rips_dionysus.py -> build/lib.linux-x86_64-3.7/topologylayer/nn
    copying topologylayer/nn/__init__.py -> build/lib.linux-x86_64-3.7/topologylayer/nn
    copying topologylayer/nn/levelset_dionysus.py -> build/lib.linux-x86_64-3.7/topologylayer/nn
    creating build/lib.linux-x86_64-3.7/topologylayer/util
    copying topologylayer/util/construction.py -> build/lib.linux-x86_64-3.7/topologylayer/util
    copying topologylayer/util/plot_dionysus.py -> build/lib.linux-x86_64-3.7/topologylayer/util
    copying topologylayer/util/__init__.py -> build/lib.linux-x86_64-3.7/topologylayer/util
    copying topologylayer/util/star_dionysus.py -> build/lib.linux-x86_64-3.7/topologylayer/util
    copying topologylayer/util/process.py -> build/lib.linux-x86_64-3.7/topologylayer/util
    copying topologylayer/util/flag_dionysus.py -> build/lib.linux-x86_64-3.7/topologylayer/util
    running build_ext
    building 'topologylayer.functional.cohom_cpp' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/topologylayer
    creating build/temp.linux-x86_64-3.7/topologylayer/functional
    creating build/temp.linux-x86_64-3.7/topologylayer/functional/cohom_cpp
    gcc -pthread -B /home/shigong/anaconda3/envs/toplayer/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/tmp/pip-req-build-epvzlx9e/topologylayer
/functional/cohom_cpp/ -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/torch/csr
c/api/include -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/TH -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/THC -I/home/shi
gong/anaconda3/envs/toplayer/include/python3.7m -c topologylayer/functional/cohom_cpp/pybind.cpp -o build/temp.linux-x86_64-3.7/topologylayer/functional/cohom_cpp/pybind.o -std=c++11 -DTORCH_API_INCLUDE_E
XTENSION_H -DTORCH_EXTENSION_NAME=cohom_cpp -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -B /home/shigong/anaconda3/envs/toplayer/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/tmp/pip-req-build-epvzlx9e/topologylayer
/functional/cohom_cpp/ -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/torch/csr
c/api/include -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/TH -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/THC -I/home/shi
gong/anaconda3/envs/toplayer/include/python3.7m -c topologylayer/functional/cohom_cpp/cohom.cpp -o build/temp.linux-x86_64-3.7/topologylayer/functional/cohom_cpp/cohom.o -std=c++11 -DTORCH_API_INCLUDE_EXT
ENSION_H -DTORCH_EXTENSION_NAME=cohom_cpp -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -B /home/shigong/anaconda3/envs/toplayer/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/tmp/pip-req-build-epvzlx9e/topologylayer
/functional/cohom_cpp/ -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/torch/csr
c/api/include -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/TH -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/THC -I/home/shi
gong/anaconda3/envs/toplayer/include/python3.7m -c topologylayer/functional/cohom_cpp/complex.cpp -o build/temp.linux-x86_64-3.7/topologylayer/functional/cohom_cpp/complex.o -std=c++11 -DTORCH_API_INCLUDE
_EXTENSION_H -DTORCH_EXTENSION_NAME=cohom_cpp -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -B /home/shigong/anaconda3/envs/toplayer/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/tmp/pip-req-build-epvzlx9e/topologylayer
/functional/cohom_cpp/ -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/torch/csr
c/api/include -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/TH -I/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/THC -I/home/shi
gong/anaconda3/envs/toplayer/include/python3.7m -c topologylayer/functional/cohom_cpp/cocycle.cpp -o build/temp.linux-x86_64-3.7/topologylayer/functional/cohom_cpp/cocycle.o -std=c++11 -DTORCH_API_INCLUDE
_EXTENSION_H -DTORCH_EXTENSION_NAME=cohom_cpp -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from topologylayer/functional/cohom_cpp/cocycle.cpp:1:0:
    topologylayer/functional/cohom_cpp/cocycle.h:10:3: error: ‘size_t’ does not name a type
In file included from topologylayer/functional/cohom_cpp/cocycle.cpp:1:0:                                                                                                                        [0/994]
    topologylayer/functional/cohom_cpp/cocycle.h:10:3: error: ‘size_t’ does not name a type
       size_t index;
       ^
    topologylayer/functional/cohom_cpp/cocycle.h: In constructor ‘Cocycle::Cocycle()’:
    topologylayer/functional/cohom_cpp/cocycle.h:17:15: error: class ‘Cocycle’ does not have any field named ‘index’
       Cocycle() : index(-1){}
                   ^
    topologylayer/functional/cohom_cpp/cocycle.h: In constructor ‘Cocycle::Cocycle(int)’:
    topologylayer/functional/cohom_cpp/cocycle.h:20:20: error: class ‘Cocycle’ does not have any field named ‘index’
       Cocycle(int x) : index(x) {cochain.push_back(x); }
                        ^
    topologylayer/functional/cohom_cpp/cocycle.h: In constructor ‘Cocycle::Cocycle(int, std::vector<int>)’:
    topologylayer/functional/cohom_cpp/cocycle.h:21:41: error: class ‘Cocycle’ does not have any field named ‘index’
       Cocycle(int x, std::vector<int> y) :  index(x) , cochain(y) {}
                                             ^
    topologylayer/functional/cohom_cpp/cocycle.cpp: In member function ‘void Cocycle::print()’:
    topologylayer/functional/cohom_cpp/cocycle.cpp:86:33: error: too many arguments to function ‘void pybind11::print(Args&& ...) [with pybind11::return_value_policy policy = (pybind11::return_value_polic
y)1u; Args = {}]’
      py::print(index, " : ", cochain);
                                     ^
    In file included from /home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/pybind.h:6:0,
                     from /home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/python.h:7,
                     from /home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/torch/extension.h:6,
                     from topologylayer/functional/cohom_cpp/cocycle.cpp:4:
    /home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/torch/lib/include/pybind11/pybind11.h:1747:6: note: declared here
     void print(Args &&...args) {
          ^
    error: command 'gcc' failed with exit status 1
  Running setup.py install for topologylayer ... error
Cleaning up...
  Removing source in /tmp/pip-req-build-epvzlx9e
Removed build tracker '/tmp/pip-req-tracker-r_iwud0j'
ERROR: Command "/home/shigong/anaconda3/envs/toplayer/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-epvzlx9e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file
__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-jn57soax/install-record.txt --single-version-externally-ma
naged --compile" failed with error code 1 in /tmp/pip-req-build-epvzlx9e/
Exception information:
Traceback (most recent call last):
  File "/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 414, in run
    use_user_site=options.use_user_site,
  File "/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 951, in install
    spinner=spinner,
  File "/home/shigong/anaconda3/envs/toplayer/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 776, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/home/shigong/anaconda3/envs/toplayer/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-epvzlx9e/setup.py'"'"';f=getattr(t
okenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-jn57soax/install-reco
rd.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-epvzlx9e/

```

**Comment by bnels** [comment]
Thanks for the report.  I also ran into this issue when testing with Travis.  This should be resolved with #11, but we'll wait for pull request to go through.

**Comment by bnels** [comment]
@gongshichina #11 has been merged with master.  Does this resolve your problem?

**Comment by gongshichina** [comment]
Yes, it worked. I cannot thank you more.You are so excellent!
