### ISSUE TITLE
ImportError: cannot import name 'SimplicialComplex'

### ISSUE THREAD

**Issue by amiltonwong** [bruel-gabrielsson/TopologyLayer#27]
Hi, @bruel-gabrielsson ,

I had followed your [guide](https://github.com/bruel-gabrielsson/TopologyLayer#optional-compiling-c-extensions)  on building C++ extensions, and the building process is finished without error. However, when import the packages as follows:

```
>>> import torch
>>> from topologylayer.nn import LevelSetLayer1D, SumBarcodeLengths

```

I got the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/code13/TopologyLayer/topologylayer/__init__.py", line 1, in <module>
    import topologylayer.nn
  File "/data/code13/TopologyLayer/topologylayer/nn/__init__.py", line 3, in <module>
    from .levelset import LevelSetLayer, LevelSetLayer1D, LevelSetLayer2D
  File "/data/code13/TopologyLayer/topologylayer/nn/levelset.py", line 1, in <module>
    from ..functional.sublevel import SubLevelSetDiagram
  File "/data/code13/TopologyLayer/topologylayer/functional/sublevel.py", line 6, in <module>
    from .persistence import SimplicialComplex, persistenceForwardCohom, persistenceBackward, persistenceForwardHom
ImportError: cannot import name 'SimplicialComplex'

```

For my another virtual environment, I use `pip install git+https://github.com/bruel-gabrielsson/TopologyLayer.git` to install it globally and the import commands run successfully.
Any hints to solve this issue?  
THX!

My system information is the following:
operating system : ubuntu 16.04
Python version, environment setup: Python 3.6.5, with conda environment

**Comment by soham0209** [comment]
Adding to the previous comment:
Installing with pip install git+https://github.com/bruel-gabrielsson/TopologyLayer.git and running your examples in jupyter notebook reproduces the problem. However if I run as: 
python3 holes.py
 The program executes successfully.

**Comment by stal12** [comment]
@amiltonwong have you tried changing the current directory? It worked for me.
Check [this answer](https://stackoverflow.com/questions/63728242/importerror-cannot-import-name-unknown-location/63728744#63728744).

**Comment by DanielNolte** [comment]
I ran into the same issues on Windows 10 with Python 3.10.4.

After creating a new environment, installing dependencies, and installing TopologyLayer, I realized the topologylayer folder was inside the .egg site-package folder:  tmp/.conda/envs/ACTIVE_ENV/lib/site-packages/topologylayer-0.0.0-py3.10-win-amd64.egg/topologylayer

To fix the issue, I moved the topologylayer folder from  tmp/.conda/envs/ACTIVE_ENV/lib/site-packages/topologylayer-0.0.0-py3.10-win-amd64.egg  to  tmp/.conda/envs/ACTIVE_ENV/lib/site-packages/, and now the import works
