### ISSUE TITLE
Cannot install the library

### ISSUE THREAD

**Issue by jmlipman** [bruel-gabrielsson/TopologyLayer#49]
Hi,

I tried to pip install TopologyLayer, as well as doing "python setup.py install --record files.txt". In both cases, I get an extremely long error. These are the very last lines:

`                 from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/extension.h:5,
                 from /zhome/72/3/199765/delete/TopologyLayer/topologylayer/functional/persistence/pybind.cpp:1:
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/options/conv.h:61:24: note: candidate: ‘decltype (*(torch::nn::detail::ConvNdOptions<D>*)this) torch::nn::detail::ConvNdOptions<D>::padding(const int&) [with long unsigned int D = 1; decltype (*(torch::nn::detail::ConvNdOptions<D>*)this) = torch::nn::detail::ConvNdOptions<1>&]’
   61 |   TORCH_ARG(padding_t, padding) = 0;
      |                        ^~~~~~~
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/arg.h:7:15: note: in definition of macro ‘TORCH_ARG’
    7 |   inline auto name(const T& new_##name) -> decltype(*this) { /* NOLINT */ \
      |               ^~~~
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/options/conv.h:61:24: note:   candidate expects 1 argument, 0 provided
   61 |   TORCH_ARG(padding_t, padding) = 0;
      |                        ^~~~~~~
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/arg.h:7:15: note: in definition of macro ‘TORCH_ARG’
    7 |   inline auto name(const T& new_##name) -> decltype(*this) { /* NOLINT */ \
      |               ^~~~
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/options/conv.h:61:24: note: candidate: ‘decltype (*(torch::nn::detail::ConvNdOptions<D>*)this) torch::nn::detail::ConvNdOptions<D>::padding(int&&) [with long unsigned int D = 1; decltype (*(torch::nn::detail::ConvNdOptions<D>*)this) = torch::nn::detail::ConvNdOptions<1>&]’
   61 |   TORCH_ARG(padding_t, padding) = 0;
      |                        ^~~~~~~
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/arg.h:11:15: note: in definition of macro ‘TORCH_ARG’
   11 |   inline auto name(T&& new_##name) -> decltype(*this) { /* NOLINT */      \
      |               ^~~~
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/options/conv.h:61:24: note:   candidate expects 1 argument, 0 provided
   61 |   TORCH_ARG(padding_t, padding) = 0;
      |                        ^~~~~~~
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/arg.h:11:15: note: in definition of macro ‘TORCH_ARG’
   11 |   inline auto name(T&& new_##name) -> decltype(*this) { /* NOLINT */      \
      |               ^~~~
In file included from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/functional/conv.h:3,
                 from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/functional.h:4,
                 from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:4,
                 from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/all.h:16,
                 from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/extension.h:5,
                 from /zhome/72/3/199765/delete/TopologyLayer/topologylayer/functional/persistence/pybind.cpp:1:
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/options/conv.h:64:18: note: candidate: ‘decltype(auto) torch::nn::detail::ConvNdOptions<D>::padding(std::initializer_list<long int>) [with long unsigned int D = 1]’
   64 |   decltype(auto) padding(std::initializer_list<int64_t> il) {
      |                  ^~~~~~~
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/options/conv.h:64:18: note:   candidate expects 1 argument, 0 provided
In file included from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules.h:20,
                 from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:7,
                 from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/all.h:16,
                 from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/extension.h:5,
                 from /zhome/72/3/199765/delete/TopologyLayer/topologylayer/functional/persistence/pybind.cpp:1:
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h: In instantiation of ‘void torch::nn::ConvNdImpl<D, Derived>::reset_parameters() [with long unsigned int D = 1; Derived = torch::nn::ConvTranspose1dImpl]’:
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:101:5:   required from ‘void torch::nn::ConvNdImpl<D, Derived>::reset() [with long unsigned int D = 1; Derived = torch::nn::ConvTranspose1dImpl]’
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:33:8:   required from here
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:105:27: error: cannot convert ‘const torch::enumtype::kFanIn’ to ‘int’
  105 |     init::kaiming_uniform_(
      |     ~~~~~~~~~~~~~~~~~~~~~~^
      |                           |
      |                           const torch::enumtype::kFanIn
  106 |         weight,
      |         ~~~~~~~            
  107 |         /*a=*/std::sqrt(5)); // NOLINT(cppcoreguidelines-avoid-magic-numbers)
      |         ~~~~~~~~~~~~~~~~~~~
In file included from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:5,
                 from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/all.h:16,
                 from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/extension.h:5,
                 from /zhome/72/3/199765/delete/TopologyLayer/topologylayer/functional/persistence/pybind.cpp:1:
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/init.h:99:17: note:   initializing argument 3 of ‘at::Tensor torch::nn::init::kaiming_uniform_(at::Tensor, double, int, int)’
   99 |     FanModeType mode = torch::kFanIn,
      |     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
In file included from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules.h:20,
                 from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:7,
                 from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/all.h:16,
                 from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/extension.h:5,
                 from /zhome/72/3/199765/delete/TopologyLayer/topologylayer/functional/persistence/pybind.cpp:1:
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h: In instantiation of ‘void torch::nn::ConvNdImpl<D, Derived>::reset_parameters() [with long unsigned int D = 3; Derived = torch::nn::Conv3dImpl]’:
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:101:5:   required from ‘void torch::nn::ConvNdImpl<D, Derived>::reset() [with long unsigned int D = 3; Derived = torch::nn::Conv3dImpl]’
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:33:8:   required from here
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:105:27: error: cannot convert ‘const torch::enumtype::kFanIn’ to ‘int’
  105 |     init::kaiming_uniform_(
      |     ~~~~~~~~~~~~~~~~~~~~~~^
      |                           |
      |                           const torch::enumtype::kFanIn
  106 |         weight,
      |         ~~~~~~~            
  107 |         /*a=*/std::sqrt(5)); // NOLINT(cppcoreguidelines-avoid-magic-numbers)
      |         ~~~~~~~~~~~~~~~~~~~
In file included from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:5,
                 from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/all.h:16,
                 from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/extension.h:5,
                 from /zhome/72/3/199765/delete/TopologyLayer/topologylayer/functional/persistence/pybind.cpp:1:
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/init.h:99:17: note:   initializing argument 3 of ‘at::Tensor torch::nn::init::kaiming_uniform_(at::Tensor, double, int, int)’
   99 |     FanModeType mode = torch::kFanIn,
      |     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
In file included from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules.h:20,
                 from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:7,
                 from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/all.h:16,
                 from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/extension.h:5,
                 from /zhome/72/3/199765/delete/TopologyLayer/topologylayer/functional/persistence/pybind.cpp:1:
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h: In instantiation of ‘void torch::nn::ConvNdImpl<D, Derived>::reset_parameters() [with long unsigned int D = 2; Derived = torch::nn::Conv2dImpl]’:
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:101:5:   required from ‘void torch::nn::ConvNdImpl<D, Derived>::reset() [with long unsigned int D = 2; Derived = torch::nn::Conv2dImpl]’
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:33:8:   required from here
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:105:27: error: cannot convert ‘const torch::enumtype::kFanIn’ to ‘int’
  105 |     init::kaiming_uniform_(
      |     ~~~~~~~~~~~~~~~~~~~~~~^
      |                           |
      |                           const torch::enumtype::kFanIn
  106 |         weight,
      |         ~~~~~~~            
  107 |         /*a=*/std::sqrt(5)); // NOLINT(cppcoreguidelines-avoid-magic-numbers)
      |         ~~~~~~~~~~~~~~~~~~~
In file included from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:5,
                 from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/all.h:16,
                 from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/extension.h:5,
                 from /zhome/72/3/199765/delete/TopologyLayer/topologylayer/functional/persistence/pybind.cpp:1:
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/init.h:99:17: note:   initializing argument 3 of ‘at::Tensor torch::nn::init::kaiming_uniform_(at::Tensor, double, int, int)’
   99 |     FanModeType mode = torch::kFanIn,
      |     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
In file included from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules.h:20,
                 from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:7,
                 from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/all.h:16,
                 from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/extension.h:5,
                 from /zhome/72/3/199765/delete/TopologyLayer/topologylayer/functional/persistence/pybind.cpp:1:
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h: In instantiation of ‘void torch::nn::ConvNdImpl<D, Derived>::reset_parameters() [with long unsigned int D = 1; Derived = torch::nn::Conv1dImpl]’:
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:101:5:   required from ‘void torch::nn::ConvNdImpl<D, Derived>::reset() [with long unsigned int D = 1; Derived = torch::nn::Conv1dImpl]’
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:33:8:   required from here
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:105:27: error: cannot convert ‘const torch::enumtype::kFanIn’ to ‘int’
  105 |     init::kaiming_uniform_(
      |     ~~~~~~~~~~~~~~~~~~~~~~^
      |                           |
      |                           const torch::enumtype::kFanIn
  106 |         weight,
      |         ~~~~~~~            
  107 |         /*a=*/std::sqrt(5)); // NOLINT(cppcoreguidelines-avoid-magic-numbers)
      |         ~~~~~~~~~~~~~~~~~~~
In file included from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:5,
                 from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/all.h:16,
                 from /xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/extension.h:5,
                 from /zhome/72/3/199765/delete/TopologyLayer/topologylayer/functional/persistence/pybind.cpp:1:
/xxxx/envs/bricks/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/nn/init.h:99:17: note:   initializing argument 3 of ‘at::Tensor torch::nn::init::kaiming_uniform_(at::Tensor, double, int, int)’
   99 |     FanModeType mode = torch::kFanIn,
      |     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/xxxx/envs/bricks/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2107, in _run_ninja_build
    subprocess.run(
  File "/appl9/python/3.10.12/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/72/3/199765/delete/TopologyLayer/setup.py", line 11, in <module>
    setup(name='topologylayer',
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/command/install.py", line 80, in run
    self.do_egg_install()
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/command/install.py", line 129, in do_egg_install
    self.run_command('bdist_egg')
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/_distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/xxxx/envs/bricks/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 870, in build_extensions
    build_ext.build_extensions(self)
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/xxxx/envs/bricks/lib/python3.10/site-packages/Cython/Distutils/build_ext.py", line 135, in build_extension
    super(build_ext, self).build_extension(ext)
  File "/appl9/python/3.10.12/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "/xxxx/envs/bricks/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 683, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/xxxx/envs/bricks/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1783, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/xxxx/envs/bricks/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2123, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
`

**Python version**: 3.10.12
**OS**: AlmaLinux 9.4
**Other packages:**
asttokens==2.4.1
connected-components-3d==3.18.0
contourpy==1.2.1
cycler==0.12.1
Cython==3.0.11
decorator==5.1.1
distlib==0.3.7
exceptiongroup==1.2.2
executing==2.0.1
filelock==3.12.2
fonttools==4.53.1
fsspec==2024.6.1
gudhi==3.10.1
h5py==3.11.0
imageio==2.35.1
ipython==8.26.0
jedi==0.19.1
jinja2==3.1.4
joblib==1.4.2
kiwisolver==1.4.5
lazy-loader==0.4
MarkupSafe==2.1.5
matplotlib==3.9.2
matplotlib-inline==0.1.7
MedPy==0.5.2
monai==1.3.2
mpmath==1.3.0
networkx==3.3
nibabel==5.2.1
numpy==1.26.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.6.20
nvidia-nvtx-cu12==12.1.105
opencv-python==4.10.0.84
packaging==24.1
pandas==2.2.2
parso==0.8.4
pexpect==4.9.0
pillow==10.4.0
platformdirs==3.9.1
POT==0.9.4
prompt-toolkit==3.0.47
ptyprocess==0.7.0
pure-eval==0.2.3
pygments==2.18.0
pyparsing==3.1.4
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.2
scikit-image==0.24.0
scikit-learn==1.5.1
scipy==1.14.1
SimpleITK==2.3.1
six==1.16.0
stack-data==0.6.3
sympy==1.13.2
threadpoolctl==3.5.0
tifffile==2024.8.24
torch==2.3.1
torchaudio==2.3.1
torchvision==0.18.1
traitlets==5.14.3
triton==2.3.1
typing-extensions==4.12.2
tzdata==2024.1
UNKNOWN==0.0.0
virtualenv==20.24.1
wcwidth==0.2.13

**Comment by Yanzi-S** [comment]
I also have this problem, have you solved it? Thanks!

**Comment by jmlipman** [comment]
No :(

**Comment by AmadeusSTQ** [comment]
The reason for this issue is that the new version ninja does not have the command:
`ninja -v`

Please modify the following file:
xxx/miniconda3/envs/xxx/lib/python3.xxx/site-packages/torch/utils/cpp_extension.py

You should ensure all
`['ninja', '-v']`
replaced by
`['ninja', '--version']`

**Comment by AmadeusSTQ** [comment]
If further encountering problem like me:

> running build_ext
building 'topologylayer.functional.persistence' extension
creating /home/stq/Research/CV/topology-gs/submodules/TopologyLayer/build/temp.linux-x86_64-cpython-310/topologylayer/functional/persistence
Emitting ninja build file /home/stq/Research/CV/topology-gs/submodules/TopologyLayer/build/temp.linux-x86_64-cpython-310/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.0
g++ -pthread -B /home/stq/miniconda3/envs/3dv/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/stq/miniconda3/envs/3dv/include -fPIC -O2 -isystem /home/stq/miniconda3/envs/3dv/include -pthread -B /home/stq/miniconda3/envs/3dv/compiler_compat -shared /home/stq/Research/CV/topology-gs/submodules/TopologyLayer/build/temp.linux-x86_64-cpython-310/topologylayer/functional/persistence/cocycle.o /home/stq/Research/CV/topology-gs/submodules/TopologyLayer/build/temp.linux-x86_64-cpython-310/topologylayer/functional/persistence/cohom.o /home/stq/Research/CV/topology-gs/submodules/TopologyLayer/build/temp.linux-x86_64-cpython-310/topologylayer/functional/persistence/complex.o /home/stq/Research/CV/topology-gs/submodules/TopologyLayer/build/temp.linux-x86_64-cpython-310/topologylayer/functional/persistence/hom.o /home/stq/Research/CV/topology-gs/submodules/TopologyLayer/build/temp.linux-x86_64-cpython-310/topologylayer/functional/persistence/pybind.o -L/home/stq/miniconda3/envs/3dv/lib/python3.10/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-cpython-310/topologylayer/functional/persistence.cpython-310-x86_64-linux-gnu.so
g++: error: /home/stq/Research/CV/topology-gs/submodules/TopologyLayer/build/temp.linux-x86_64-cpython-310/topologylayer/functional/persistence/cocycle.o: No such file or directory
g++: error: /home/stq/Research/CV/topology-gs/submodules/TopologyLayer/build/temp.linux-x86_64-cpython-310/topologylayer/functional/persistence/cohom.o: No such file or directory
g++: error: /home/stq/Research/CV/topology-gs/submodules/TopologyLayer/build/temp.linux-x86_64-cpython-310/topologylayer/functional/persistence/complex.o: No such file or directory
g++: error: /home/stq/Research/CV/topology-gs/submodules/TopologyLayer/build/temp.linux-x86_64-cpython-310/topologylayer/functional/persistence/hom.o: No such file or directory
g++: error: /home/stq/Research/CV/topology-gs/submodules/TopologyLayer/build/temp.linux-x86_64-cpython-310/topologylayer/functional/persistence/pybind.o: No such file or directory
error: command '/usr/bin/g++' failed with exit code 1

I recommend you to try the following script:

> #!/bin/bash
CXX=g++
CXXFLAGS="-std=c++17 -fPIC -O2 -D_GLIBCXX_USE_CXX11_ABI=0"
INCLUDES="-I/home/stq/miniconda3/envs/3dv/include/python3.10 -I/home/stq/miniconda3/envs/3dv/lib/python3.10/site-packages/torch/include -I/home/stq/miniconda3/envs/3dv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/stq/miniconda3/envs/3dv/lib/python3.10/site-packages/torch/include/TH -I/home/stq/miniconda3/envs/3dv/lib/python3.10/site-packages/torch/include/THC"
SRCDIR=topologylayer/functional/persistence
OUTDIR=build/temp.linux-x86_64-cpython-310/topologylayer/functional/persistence
mkdir -p $OUTDIR
SOURCES=("pybind.cpp" "cohom.cpp" "hom.cpp" "complex.cpp" "cocycle.cpp")
for src in "${SOURCES[@]}"; do
  obj="${src%.cpp}.o"
  echo "Compiling $src -> $obj"
  $CXX $CXXFLAGS $INCLUDES -c $SRCDIR/$src -o $OUTDIR/$obj
done

This script will generate ".o" files manually avoid using ninja.

**Comment by AmadeusSTQ** [comment]
After generating ".o" files, then you can use the new setup.py to compile the whole project using ninja:

> from setuptools import setup
import torch, os
import sysconfig
from torch.utils.cpp_extension import CppExtension, BuildExtension, include_paths
this_dir = os.path.dirname(os.path.realpath(\__file\__))
include_dir = os.path.join(this_dir, 'topologylayer/functional/persistence/')
python_include = sysconfig.get_paths()["include"]
torch_includes = include_paths()
all_include_dirs = [include_dir, python_include] + torch_includes
extra_compile_args = ['-std=c++17']
setup(
    name='topologylayer',
    packages=[
        'topologylayer',
        'topologylayer.functional',
        'topologylayer.nn',
        'topologylayer.util'
    ],
    ext_modules=[
        CppExtension(
            name='topologylayer.functional.persistence',
            sources=[
                'topologylayer/functional/persistence/pybind.cpp',
                'topologylayer/functional/persistence/cohom.cpp',
                'topologylayer/functional/persistence/hom.cpp',
                'topologylayer/functional/persistence/complex.cpp',
                'topologylayer/functional/persistence/cocycle.cpp',
            ],
            include_dirs=all_include_dirs,
            extra_compile_args=extra_compile_args
        )
    ],
    cmdclass={'build_ext': BuildExtension},
    zip_safe=False
)

In my case, this method can directly use ".o" files from:
> build/temp.linux-x86_64-cpython-310/topologylayer/functional/persistence

**Comment by AmadeusSTQ** [comment]
Finally, if you follow my solution to pre-generate the ".o" files, please specify the Macro name defined in "topologylayer/functional/persistence/pybind.cpp" before running my script.

Change:
`PYBIND11_MODULE(TORCH_EXTENSION_NAME, m)`
to
`PYBIND11_MODULE(persistence, m)`

You can use the following command to check:
`nm -D build/lib.linux-x86_64-cpython-310/topologylayer/functional/persistence.cpython-310-x86_64-linux-gnu.so | grep PyInit`

The desired output is like
`000000000002d620 T PyInit_persistence`
rather than like
`000000000002d620 T PyInit_TORCH_EXTENSION_NAME`

**Comment by jordandekraker** [comment]
I'm having the same problems and when i try to use your script to generate ".o" files, I get the following:

```
Compiling pybind.cpp -> pybind.o
topologylayer/functional/persistence/pybind.cpp:1:10: fatal error: torch/extension.h: No such file or directory
    1 | #include <torch/extension.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
Compiling cohom.cpp -> cohom.o
topologylayer/functional/persistence/cohom.cpp:2:10: fatal error: torch/extension.h: No such file or directory
    2 | #include <torch/extension.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
Compiling hom.cpp -> hom.o
topologylayer/functional/persistence/hom.cpp:1:10: fatal error: torch/extension.h: No such file or directory
    1 | #include <torch/extension.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
Compiling complex.cpp -> complex.o
In file included from topologylayer/functional/persistence/complex.cpp:1:
topologylayer/functional/persistence/complex.h:13:10: fatal error: torch/extension.h: No such file or directory
   13 | #include <torch/extension.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
Compiling cocycle.cpp -> cocycle.o
In file included from topologylayer/functional/persistence/cocycle.h:6,
                 from topologylayer/functional/persistence/cocycle.cpp:1:
topologylayer/functional/persistence/sparsevec.h:8:10: fatal error: torch/extension.h: No such file or directory
    8 | #include <torch/extension.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Note i also tried updating the paths and python version (3.12) to match my own miniconda

Any advice?

**Comment by ShahariarRabby** [comment]
Same issue. Can not insatll.

**Comment by Flashwar** [comment]
For those who couldn’t get it installed, here is a simple fix:

In setup.py, replace:
`extra = {'cxx': ['-std=c++14']}` 
with 
`extra = {'cxx': ['-std=c++17', '-w', '-DTORCH_API_INCLUDE_EXTENSION_H', '-D_GLIBCXX_USE_CXX11_ABI=1']}`

Then install with:
`pip install -e . --no-build-isolation`

Newer PyTorch headers changed the API for kFanIn and padding() in a way that's incompatible with C++14. Upgrading to C++17 and adding the ABI compatibility flag fixes the type mismatch errors.

@ShahariarRabby
